VSCodium/vscodium

- README.md
> Update README.md to mention downloads during build

- README.md
> Add package manager instructions

- check_tags.sh
> do not hard code the repository

- install_deps.sh
While using the script I realized that the package jq was missing
> adding missing dependency jq

- DOCS.md
- README.md
> Separate out more technical docs into DOCS.md

- DOCS.md
Might close #51 but should be in the docs anyway.
> Add section for vscodium terminal support

- .gitignore
- azure-pipelines.yml
- build.sh
- check_tags.ps1
Start of Azure Pipelines for Windows Builds, need release publishing!
> Set up CI with Azure Pipelines

- create_zip.sh
> Use VSCodium in name of zip/tar

- .travis.yml
- install_deps.sh
> Fix linux 32 bit builds

- DOCS.md
> Update DOCS.md to include link to workaround for code-settings-sync

- DOCS.md
> Add workaround docs for C# extension woes

- .travis.yml
- build.sh
- install_deps.sh
(Hopefully!) Fixes arm64 build for Travis and improves the ia32 build.
> Fix arm64 build

- README.md
> Add note about flatpak

- .travis.yml
- sum.sh
- win32-build.yml
> Add hash digests to releases

- README.md
> Add donate section

- update_settings.sh
Closes #123 
Default settings will be set properly on next release after merging this PR.
> Update logic to disable telemetry and crash reporting settings

- build.sh
Fixes #115 for future builds.
Sets `win32x64UserAppId` to `2E1F05D1-C245-4562-81EE-28188DB6FD17`, a GUID I generated today.
> Set win32x64UserAppId to a unique GUID

- .travis.yml
- VSCodium-AppImage-Recipe.yml
- build.sh
- create_appimage.sh
Closes #101 
Thanks to @probonopd for the bulk of the work :pray:
> AppImage support

- build.sh
Another step for #41 
Also cleaned up how we edit the `product.json` file for future changes to be easier to reason about.
> Add quality to product.json

- build.sh
> Add keymap urls to product.json

- build.sh
Closes #41 (until further notice)
> Add updateUrl and releaseNotesUrl to product.json

- README.md
> Add more info to more info

- build.sh
> Add extensionAllowedBadgeProviders to product.json

- sum.sh
> Add sha256 sum for AppImage

- build.sh
I believe this should fix #178. Unfortunately I haven't tested it because of a gulp error.
> change icon name to vscodium.png

- win32-build.yml
> Set BUILD_SOURCEVERSION to the MS commit

- build.sh
> Add documentation and introductory videos urls

- build.sh
> Add additional urls to product.json

- .travis.yml
- check_tags.sh
- create_zip.sh
- install_deps.sh
- sum.sh
- update_version.sh
> Remove Linux 32-bit code paths

- build.sh
> Remove & from win32ShellNameShort

- update_settings.sh
Fixes #273
Output after running update_settings.sh on the latest code from `vscode`:
```
diff --git a/src/vs/platform/telemetry/common/telemetryService.ts b/src/vs/platform/telemetry/common/telemetryService.ts
index 8e64e8e045..f58e5c151d 100644
--- a/src/vs/platform/telemetry/common/telemetryService.ts
+++ b/src/vs/platform/telemetry/common/telemetryService.ts
@@ -200,7 +200,7 @@ Registry.as<IConfigurationRegistry>(Extensions.Configuration).registerConfigurat
'telemetry.enableTelemetry': {
'type': 'boolean',
'description': localize('telemetry.enableTelemetry', "Enable usage data and errors to be sent to a Microsoft online service."),
-                       'default': true,
+                       'default': false,
'tags': ['usesOnlineServices']
}
}
diff --git …
```
> Update path to crash reporter setting

- VSCodium-AppImage-Recipe.yml
- src/resources/linux/appimage/pkg2appimage
- sum.sh
Have confirmed AppImage gets created on my branch. Closes #299 and #253 thanks to @tyu1996
> Fix appimage

- DOCS.md
- build.sh
- patches/update-cache-path.patch
Accidentally branched off #300; commits will clean up when #300 is merged
This closes #254
> Update cache path

- create_dmg.sh
> Remove space from dmg filename

- update_settings.sh
The file containing the setting changed.
> Fix telemetry.enableCrashReporter setting

- .github/workflows/macos.yml
- build.sh
MS looking to support Mac ARM builds, so the gulp task was renamed.
Ref:
- https://github.com/microsoft/vscode/blob/master/build/azure-pipelines/darwin/product-build-darwin.yml#L141
- https://github.com/microsoft/vscode/blob/master/build/azure-pipelines/product-build.yml#L167
> Include arch in Darwin build task

- LICENSE
> Updated license year.

- patches/binary-name.patch
- patches/custom-gallery.patch
- patches/fix-rpm-spec.patch
- patches/update-cache-path.patch
This PR is updating the patches for 1.55. 
Thank you @atesca09 for having started the updates.
> fixing build for 1.55

- patches/custom-gallery.patch
Updating the custom-gallery.patch for 1.56
> Fix custom gallery patch for 1.56

- DOCS.md
- patches/custom-gallery.patch
This PR is fixing the path of the custom `product.json` to customize the gallery. #719
I've updated `DOCS.md` to list all possible paths.
> fix custom gallery on windows

- patches/user/readme.txt
- prepare_vscode.sh
> Add ability to apply user specific patches to vscode source

- build.sh
This PR is fixing the markdown preview's issue #694 by building the required media files used by it.
> fix markdown's preview

- .github/workflows/linux.yml
- .github/workflows/macos.yml
- .github/workflows/windows.yml
- patches/custom-gallery.patch
fixing build vor version 1.58.0
> Fix custom-gallery patch

- VSCodium-AppImage-Recipe.yml
- create_appimage.sh
> Fixing python in AppImage

- prepare_vscode.sh
This PR is adding a loop to apply patches.
> add a loop to apply patches

- get_repo.sh
Add support to build latest insider commit
> Add support to build insider latest build: $ INSIDER=1 ./build/build_mac.sh

- patches/fix-cors.patch
- prepare_vscode.sh
This PR is fixing #746 by reverting the CORS checks (added in `v1.58`). 
Additionally, it's adding a loop to apply patches.
@stripedpajamas If by the `v1.59.0`, the CORS haven't being added to openvsx, we should apply this PR.
> Fix extension marketplace

- .gitignore
- build/build_windows.ps1
- build/build_windows.sh
- docs/build.md
- prepare_vscode.sh
This PR is providing the following improvements:
- add some temp files to `.gitignore`
- reduce logs when applying patches
- avoid possible conflict on Windows with WSL
- add script to build with WSL
> add some small improvements

- patches/custom-gallery.patch
This PR is fixing the custom gallery for 1.60
> fix(1.60): update custom gallery patch

- .github/workflows/linux.yml
The PR should ignore AppImage artifacts on arm
> ci(linux): copy should ignore missing files

- .github/workflows/linux.yml
- .gitignore
- build.sh
- build/linux/appimage/build.sh
- build/linux/appimage/recipe.yml
This PR is reorganizing the appimage files so that the project is cleaner.
>  build(linux): reorganizing appimage build

- check_tags.sh
This PR is fixing a filename in `check_tags.sh`.
> fix: correct filename

- check_tags.sh
This PR is fixing a bad check...
> fix: check of armhf rpm

- .github/workflows/macos.yml
- .github/workflows/windows.yml
- release.sh
> fix: correctly read exit status

- .github/workflows/linux.yml
- README.md
- stores/snapcraft/check_deploy.sh
- stores/snapcraft/deploy.sh
- stores/snapcraft/snap/local/bin/electron-launch
- stores/snapcraft/snap/snapcraft.yaml
This PR is building and publishing the snaps as soon as the binaries are published.
> feat: publish snap

- DOCS.md
- README.md
DOCS.md:85,91: offical -> official
README.md:130: limitted -> limited
> Fix typos in DOCS.md and README.md

- DOCS.md
This PR is adding a doc for the issue #409.
> docs: how to fix default file manager on linux

- .editorconfig
- src/src/vs/workbench/browser/parts/editor/media/letterpress-dark.svg
- src/src/vs/workbench/browser/parts/editor/media/letterpress-hc.svg
- src/src/vs/workbench/browser/parts/editor/media/letterpress.svg
> fix: update size of  letterpress images

- build/linux/appimage/recipe.yml
This PR is re-fixing the issue #854
> fix(appimage): remove unnecessary glib

- stores/snapcraft/check_version.sh
This PR is adding debug infos due to the recent error when publishing the snap.
> fix(snap): add debug infos

- README.md
- remove old Azure shield
- add GH Workflow shield per platform
> docs: update CI shields in README.md

- prepare_vscode.sh
- product.json
This PR is adding the missing properties related to extensions in the `product.json`.
> fix: add missing extensionEnabledApiProposals and more

- patches/fix-builtin-extensions.patch
This PR is a temporary fix to disable updating the builtin extensions.
> fix: disable updating the builtin extensions

- prepare_vscode.sh
> Fix 'Report Issue' GitHub URL.

- .github/workflows/lock.yml
This PR is fixing the config of the workflow to lock old issues/pr.
> vcs: fix lock workflow config

- docs/build.md
Remove second mention of libsecret-1 as a Linux build dependency
> Remove repeated dependency

- build.sh
This PR fixes the time of built files so it isn't set to 12/31/1979.
Resolves: #1080
> fix: set the built files at the built time

- .github/workflows/insider-linux.yml
- .github/workflows/insider-macos.yml
- .github/workflows/insider-spearhead.yml
- .github/workflows/insider-windows.yml
- .github/workflows/stable-linux.yml
- .github/workflows/stable-macos.yml
- .github/workflows/stable-windows.yml
- build.sh
- build/build.sh
- prepare_artifacts.sh
> refactor: move artifacts building and signing into prepare_artifacts.sh

- .gitignore
- build/build.sh
- build/build_docker.sh
- build/linux/appimage/build.sh
- build/windows/msi/build.sh
- build/windows/msi/i18n/vscodium.de-de.wxl
- build/windows/msi/i18n/vscodium.en-us.wxl
- build/windows/msi/i18n/vscodium.es-es.wxl
- build/windows/msi/i18n/vscodium.fr-fr.wxl
- build/windows/msi/i18n/vscodium.it-it.wxl
- build/windows/msi/i18n/vscodium.ja-jp.wxl
- build/windows/msi/i18n/vscodium.ko-kr.wxl
- build/windows/msi/i18n/vscodium.ru-ru.wxl
- build/windows/msi/i18n/vscodium.zh-cn.wxl
- build/windows/msi/i18n/vscodium.zh-tw.wxl
- prepare_artifacts.sh
> fix: generate artifacts

- README.md
Noticed the logo was a dead link on my profile, so I fixed it pointing to the wrong path since PR #1217
> Fix README logo

- .github/workflows/insider-macos.yml
More details at https://github.com/actions/runner-images/issues/5583
> ci: use not deprecated macOS

- stores/snapcraft/check_version.sh
> fix(snap): no info if no release [skip ci]

- get_repo.sh
- prepare_vscode.sh
- src/insider/resources/win32/VisualElementsManifest.xml
- src/stable/resources/win32/VisualElementsManifest.xml
Some Microsoft copyrights and publisher were left around...
> fix: set VSCodium as the publisher

- stores/snapcraft/insider/snap/snapcraft.yaml
- stores/snapcraft/stable/snap/snapcraft.yaml
> Enables Wayland in snap builds

- patch.sh
- patches/update-msi.patch
This is an attempt to fix the update on MSI.
> fix: update msi

- README.md
This is updating the list of downloaded pre-built packages.
It finishes the PR #1095.
> doc: update downloaded files

- .github/workflows/insider-linux.yml
- .github/workflows/stable-linux.yml
- .gitignore
- build.sh
- install_remote_dependencies.sh
The PR is fixing the file permissions of the remote dependencies.
> fix: remote dependencies

- patches/win7.patch
This PR re-enables `.exe` to be compatible with Windows 7.
> feat(1.74): support windows 7

- patches/feat-announcements.patch
Fixes #1332 #1379.
PS. In some areas of mainland China, `raw.githubusercontent.com` will be resolved to `0.0.0.0`. This also leads to `Failed to fetch` error.
> fix: cannot open welcome page when offline

- patches/brand.patch
This PR fixes the webview by removing the changes made to the error message.
Resolves:  #1502 #1503 #1504 #1507 #1508 #1510
> fix: make webview works again

- prepare_assets.sh
The gulp action has been removed...
> fix(win32): build archive

- build/update_api.sh
- product.json
This PR resolves jeanp413/open-remote-wsl#1
@jeanp413
> feat: add apis for open-remote-wsl extension

- CONTRIBUTING.md
- docs/accounts-authentication.md
- docs/howto-build.md
- docs/index.md
- docs/troubleshooting.md
This PR fixes some typos in various documentation files.
> Fixes typos in various doc files

- README.md
Add link to microsoft/vscode repo to easily find original source.
> Add vscode link in README.md

- docs/extensions-compatibility.md
basedpyright is a fork of pyright i maintain that includes some pylance features built into the language server.
> add basedpyright to alternative extensions list

- .github/workflows/insider-windows.yml
This PR is signing the `.exe` artifacts with [signpath.io](https://about.signpath.io/) and their support of open source projects.
> feat: signing windows .exe

- .github/workflows/insider-linux.yml
- .github/workflows/insider-windows.yml
- .github/workflows/stable-linux.yml
- build.sh
- package_windows.sh
This PR is moving to the following steps:
- on Linux:
- compile
- then on Windows:
- download the compiled js
- install the dependencies
- do the final packaging.
Issues: #2068
> build(windows): pre-compile on linux

- patches/extensions-disable-mangler.patch
This PR takes #1582 but merges it in the Insiders version.
> feat: remove mangling in extensions

- .github/workflows/insider-linux.yml
- .github/workflows/stable-linux.yml
- patches/update-electron.patch
> fix(linux): update electron to fix menu bug

- stores/snapcraft/insider/snap/snapcraft.yaml
- stores/snapcraft/stable/snap/snapcraft.yaml
> feat(snap): add audio playback

- build.sh
- dev/patch.sh
- patches/windows/policies.patch
The PR adds policies for windows
References:
- #2207
> feat: add patch to use policies

- release_notes.txt
> docs: fix release links

- patches/linux/yarn-dependencies.patch
Fixes #2261
Also adds an option to disable this QEMU step by `export DISABLE_QEMU=true`
> Fix error with qemu and ppc64le segfaults on build reh

- patches/version-1-update.patch
> feat(linux): allow update check

- patches/feat-announcements.patch
- patches/feat-ext-unsafe.patch
- patches/version-1-update.patch
> fix: add property to disable extra connection

- patches/chat.patch
- patches/feat-announcements.patch
- patches/feat-ext-unsafe.patch
- patches/version-0-release.patch
- patches/version-1-update.patch
This PR includes:
- #2324
- #2327
- #2334
- #2335
> fix: pick tested PR from Insiders

- docs/telemetry.md
Add feedback preference to "Additional Privacy Settings" section.
> Update telemetry docs

- stores/snapcraft/insider/snap/snapcraft.yaml
- stores/snapcraft/stable/snap/snapcraft.yaml
> fix: sort with number map instead of string
