VSCodium/vscodium

- README.md
- build.sh
- undo_telemetry.sh
- update_settings.sh
This addresses Issue #44 by setting the default `telemetry.enableCrashReporter` and `telemetry.enableTelemetry` values to false in the undo_telemetry post install script.
> Replace telemetry default true values in settings.json

- .travis.yml
- trigger-azure.sh
Have it set to only trigger from Mac build, and only if we actually built (and Azure token is present), which should stop us from queueing up more than build per Travis batch.
Tested locally that the curl command does in fact queue up an Azure build.
Closes #68
> Add script to trigger Azure pipelines build

- .travis.yml
- azure-pipelines.yml
- build.sh
- check_tags.ps1
- win32-build.yml
Made `build.sh` easier to reason about and setup pipeline for building Windows 32-bit binaries. The binaries haven't been tested on 32-bit machines but the build process went smoothly.
> Build cleanup and Windows ia32

- DOCS.md
Update the DOCS.md file to refer to a external gentoo overlay as stated on #111 plus minor markdown linting
> Docs update

- check_tags.sh
The current check collides with the Windows zip file, so a race condition could exist where a Windows build finishes before a Mac build checks if it should build.
> Update check for Mac artifact

- build.sh
- Update to use new gulp tasks
- Wrap `yarn gulp minify-vscode` in a `keep_alive` script so that Travis doesn't give up after 10 minutes
Max execution time for a public repo build is 50 minutes, and sometimes the Darwin build exceeds that. We will need to find some ways of trimming down that time to make these builds safer.
> Update build process

- build.sh
Have confirmed that the produced Windows assets have proper commit hash in product.json
Fixes #222 
Will take affect in next released build.
> Set BUILD_SOURCEVERSION to LATEST_MS_COMMIT explicitly

- .travis.yml
- trigger-azure.sh
It appears that Azure Pipelines is now able to keep up with running scheduled builds, so triggering an extra build causes a race condition.
> Stop triggering Azure

- .travis.yml
"As of August, 13th 2019, we’ve switched the default Linux distribution on Travis CI from Ubuntu Trusty 14.04 LTS to Ubuntu Xenial 16.04. Here are the most common issues our customers ran into and how you can fix them." - https://docs.travis-ci.com/user/trusty-to-xenial-migration-guide
Tested and fixed the version of Ubuntu used by TravisCI to Ubuntu 14 (trusty), as the default changed in August (and broke compatibility with RHEL 7, CentOS 7, and deviated from VS Code's official builds).
> Update TravisCI config to use Ubuntu 14.04

- .travis.yml
- README.md
- build.sh
- install_deps.sh
- sum.sh
The `build.sh` changes can be cleaned up a little bit thanks to https://github.com/microsoft/node-native-keymap/commit/e31be382147decfbdf943ba0e63acc920098fd06 and https://github.com/microsoft/vscode/pull/86659 (by using `PKG_CONFIG=pkg-config-aarch64-linux-gnu`), but it would be better to give something to those desiring a working arm64 build, then iterate from there.
> Add hacky, initial arm64 support

- .travis.yml
- README.md
- build.sh
- check_tags.sh
- create_zip.sh
- install_deps.sh
- sum.sh
This is a superset of #302 that fixes the rest of #6, by adding 32-bit (ARMv7) support.
~~I opened a separate PR, since there's a possibility that it's going to take time for me to fix the ARMv7 hardware I can test this on. File sizes (.deb, .tar.gz, etc') look sane, though.~~
~~I'll test this on my arm64 Chromebook, with 32-bit support libraries installed.~~
Tested on my RK3288 Chromebook (Cortex A 17).
> Add hacky, initial armhf support

- DOCS.md
Closes #333
> Updated portable mode description. OS Instructions are now separated with bullet points. Added a hyperlink to "link above".
Please accept my pull-request 🍀
> :scroll: portable mode description

- DOCS.md
https://github.com/shanalikhan/code-settings-sync/issues/668#issuecomment-505142734
> Remove sync workaround

- prepare_vscode.sh
The two commits enable the `ms-vscode-remote.remote-ssh` API and set the `serverDataFolderName` key<sup>[1]</sup> in `product.json`, required for Microsoft's Remote SSH extension to function. Note that the server will try to validate the "client handshake," which you will have to patch manually at your own risk (mentioned in their [FAQ](https://github.com/microsoft/vscode/wiki/Differences-between-the-repository-and-Visual-Studio-Code#what-goes-where>)). This PR is what we can do from the editor side without violating any license.
Tested to work on x86-64, with Remote SSH connected to a x86-64 host.
<sup>[1]</sup> If `serverDataFolderName` is not set, the extension will always select the insider version of the server binary, causing a version mismatch when connecting.
> product.json changes for Remote SSH

- prepare_vscode.sh
Fix vscode sqlite error that makes welcome messages (notification, extension welcome pages) appear every time on vscode startup.
> Fix sqlite error on ARM build

- prepare_vscode.sh
Without this property present, VSCode will not show the "Don't show this
again" button when integrity checks fail. This commit fixes #326
> Add checksumFailMoreInfoUrl to product.json

- prepare_vscode.sh
*   C++ tools
*   Python
*   Docker
*   Intellicode
Not all functions can be enabled by this subtle modification. For instance, you still can't use pylance.
> Add more proposed APIs

- patches/no-replace-product-json.patch
- prepare_vscode.sh
If product.json is modified locally, say, to change gallery url, in each updates, the product.json is replaced by the vanilla one, which makes some troubles. This patch prevents that issue in RPM builds by marking `noreplace` on it. Not sure whether other packaging formats have similiar feature.
> Don't replace product.json in RPM updates

- .github/workflows/linux.yml
- .github/workflows/macos.yml
GitHub now enforcing no `set-env` or `add-path` calls: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
The `set-env` calls in macos.yml were already redundant; we were doing the new way (`echo "key=val" >> $GITHUB_ENV`) in `check_tags.sh` and `get_repo.sh`. 
`actions/setup-node` updated to env files in 1.4.4, but our workflow was locked at 1.4.3. Removed the spec lock to pick up the latest minor versions going forward.
> Fix actions

- check_tags.sh
This PR fixes `check-tags.sh` where the architecture type in the archive name is missing.
> fix check-tags.sh on macos

- README.md
The process to install macOS packages through Homebrew Cask has changed.
> Fixed macOS install instructions

- update_version.sh
This PR adds `VSCODE_ARCH` to the archive and to `VERSION_PATH ` but not sure if it's correct...
> fix update_version.sh on macos

- README.md
macOS since 2016. OSX name changed 4 years ago.
> OS X -> macOS | since 2016

- README.md
* adds some minimal versions, along with the reason for it (at least I was tempted to say "we could go further than Visual Studio Code" - but we actually can't because of Electron
* adds arm64 macOS status
* adds Windows arm64 which is actually provided since some time
Note: I highly suggest to change "supported OS" to "supported platforms" as "Linux" is no OS but a kernel and we explicit mention the processors, too (I personally also think GNU/Linux would be better in this context).
If approved I'd also do both these changes and force-push so we have a single commit for this @stripedpajamas your decision.
> supported platform update, fixes #648

- patches/fix-rpm-spec.patch
- patches/no-replace-product-json.patch
- prepare_vscode.sh
This PR is removing the compatibility for Centos 7 since it isn't supported by Electron 11 (https://code.visualstudio.com/updates/v1_53#_electron-11-update).
> remove Centos 7 compatibility

- check_cron_or_pr.sh
This PR is fixing a regression introduced in #666 which blocks the creation of any new release...
It's correctly determining when the run is a PR or not.
> fix schedule runs

- build/build_windows.ps1
- patches/binary-name.patch
- prepare_vscode.sh
This PR is patching the binary name to use `product.applicationName` instead of being static.
It should fix #509.
For #654, it needs further informations.
> patch static binary name

- update_settings.sh
This PR is detecting the `sed` version (gnu or macos) instead of using the env variable `OS_NAME`.
It's useful when manually building the project on macOS where `sed` has been replaced with its gnu variant.
> detect sed version

- patches/update-cache-path.patch
Seems more appropriate, since `nameShort` is intended to be user-facing and could e.g. contain spaces.
> Use `applicationName` for update cache path

- .github/workflows/linux.yml
- create_appimage.sh
- docs/build.md
This PR is moving the dependency installation into workflow so non-Debian-based Linux can build the AppImage without the need to edit the bash script.
> Fix AppImage's dependency

- patches/crash-reporter.patch
The PR is fixing the change between [Electron 13](https://github.com/electron/electron/blob/v13.1.7/docs/api/crash-reporter.md) and [Electron 12](https://github.com/electron/electron/blob/v12.0.13/docs/api/crash-reporter.md) where `submitURL` becomes a requirement.
This is a last minute change found on the `1.59`, I'm pushing the merge before the build process.
> do not start crashReporter when appCenter isn't configured

- prepare_vscode.sh
This PR is fixing the test so the build fails when a patch can't be applied.
> fix: fail build when a patch can't be applied

- patches/disable-cors.patch
This PR is editing the patch to disable CORS so that internal pages can be loaded successfully (ex: issue report).
> fix: correctly load internal pages

- check_tags.sh
This PR is fixing the error `Cannot iterate over null` due to no assets in the tag or the tag doesn't exist.
> fix: don't loop when there is no assets in the tag

- check_tags.sh
This PR is adding the missing check.
> fix(linux): correctly check if the AppImage has been built

- .github/workflows/macos.yml
This PR is removing the macOS arm64 build until something else can do it since I'm not able to test it.
> fix: remove macos arm64 build

- README.md
Hi everyone, I like when projects have build instructions right in the README.md file, and when it is not possible, at least it shows where to go without having to go through files to find it.
> indicate build documentation

- patches/cleanup-archive.patch
This PR removes superfluous files from windows' archives. (#573)
> build(win): remove superfluous files from archive

- .gitignore
- build/linux/appimage/recipe.yml
This PR is making AppImage runnable on Arch, Fedora and ... by removing extraneous libs.
> fix: appimage

- README.md
The built-in js debugging extensions have changed. See #980
> docs: update built-in package names

- .github/workflows/linux.yml
The PR is fixing a mistake so the snap isn't tried to be built for arm64 in favor of a release for x64.
> ci: disable snap for arm64

- update_settings.sh
The PR is removing the deprecated `telemetry.enableTelemetry`.
It's an update after a review of #1029.
> refactor: remove deprecated `telemetry.enableTelemetry`

- .github/workflows/linux.yml
- .github/workflows/macos.yml
- .github/workflows/windows.yml
Bump GitHub Actions to their latest major versions. Main change is they're now using Node 16 instead of 12, which is EOL at end of month.
- Changelog for `actions/checkout` can be [found here](https://github.com/actions/checkout/blob/main/CHANGELOG.md)
- Releases for `actions/setup-node` can be [found here](https://github.com/actions/setup-node/releases)
- Releases for `actions/cache` can be [found here](https://github.com/actions/cache/releases)
- Releases for `actions/setup-python` can be [found here](https://github.com/actions/setup-python/releases)
> ci: bump github actions

- .github/workflows/lock.yml
This PR is adding a workflow which locks the closed issues older than 90 days.
> vcs: add workflow to lock old closed issues

- stores/snapcraft/check_version.sh
Regex passed to grep frequently contains characters that collide with globs, quoting it stops that from happening.
> build(stores/snapcraft): quote grep pattern so shell won't interpret it

- build.sh
This PR generates the missing `out` directory in the REH binaries.
> fix: generate mssing `out` directory

- .github/workflows/linux.yml
- stores/snapcraft/check_version.sh
This PR uses the  environment variable `SNAPCRAFT_STORE_CREDENTIALS` since we are getting the following error:
```
/snap/bin/snapcraft login --with /tmp/login-data-UK8Fip/login.txt
--with is no longer supported, export the auth to the environment variable 'SNAPCRAFT_STORE_CREDENTIALS' instead     
```
> fix: use env variable instead of `login` option

- build/update_patches.sh
- docs/build.md
This PR adds a simple script to update the patches more easily.
It loops over over the patches and when a patch fails then:
- it apply the patch and generates the `.rej` files
- pause the script until the user has resolved all the conflicts
- when a key has been pressed, it generates the `.patch` file
> feat: add script to update patches

- .gitignore
- build/update_api.sh
- product.json
This PR updates the `extensionEnabledApiProposals` property in the `product.json`
It also adds the script `build/update_api.sh` which update that property from VSCode.
Fixes #1184
> fix: update api proposals

- .github/workflows/linux.yml
- .github/workflows/macos.yml
- .github/workflows/windows.yml
- build/windows/msi/build.sh
- check_cron_or_pr.sh
- check_tags.sh
- get_repo.sh
- patches/build-version.patch
- patches/custom-gallery.patch
- prepare_artifacts.sh
- prepare_vscode.sh
- release.sh
- update_settings.sh
- update_version.sh
- utils.sh
- version.sh
This PR adds a release number to each build.
It will allow us to release a new version when we find and correct a bug.
It will also be the base to generate insiders release.
The version number becomes like `1.70.1.22226` with the parts:
- `1.70.1`: the old version number (from VSCode)
- `.`: required separator for MSI, [RPM](https://docs.fedoraproject.org/en-US/packaging-guidelines/Versioning/)
- `22`: the year on 2 digits ([MSI](https://docs.microsoft.com/en-us/windows/win32/msi/productversion) requires a number less than 65,535)
- `226`: the day of year
> feat: add release number

- docs/build.md
- undo_telemetry.sh
This PR removes the need of the external dependency of ripgrep.
> build(linux): use vscode's ripgrep

- patch.sh
- patches/build-version.patch
This PR update the issue generator with the release number and the correct app name.
It also adds a helper script to update a single patch.
> fix: update issue reporter

- utils.sh
- version.sh
This PR is reducing the use of `npm install -g` which can be any issue for some package managers.
> fix: install checksum only when needed

- .github/workflows/linux.yml
This PR reenables the snap for arm64 after the updates:
- https://github.com/diddlesnaps/snapcraft-container/pull/17
- https://github.com/diddlesnaps/snapcraft-multiarch-action/pull/7
> ci(snap): re-enable arm64

- .github/workflows/insider-linux.yml
- .github/workflows/insider-macos.yml
- .github/workflows/insider-spearhead.yml
- .github/workflows/insider-windows.yml
- .github/workflows/stable-linux.yml
- .github/workflows/stable-macos.yml
- .github/workflows/stable-windows.yml
Hi,
I'm moving the schedule of the workflows:
- `stable` at `18:00`. So if there is a breaking change, the fix can be released the next day (if it's at `0:00`, we have to wait for 24h for the next possible release)
- `insider` at `6/7:00`. They are usually in the morning, at bit before that time.
> ci: improve schedule

- DOCS.md
> update concerning extension gallery

- build/update_api.sh
- product.json
This PR is adding default apis for [open-remote-ssh](https://open-vsx.org/extension/jeanp413/open-remote-ssh) so it works out of the box.
https://github.com/jeanp413/open-remote-ssh/issues/37
> feat: add default apis for open-remote-ssh

- README.md
> Fix broken workflow badges

- patches/fix-mangle-windows.patch
This PR adds a patch to fix a mixup when mangling typescript files on Windows.
`esbuild` generates paths with `\` separator while the mangler uses `/`, so the content can't be updated since the paths aren't matching
Fixes https://github.com/jeanp413/open-remote-ssh/issues/44
VSCode doesn't suffer from this issue since the typescript files are compiled once (on Ubuntu) and then shared when the different versions are built for each platform...
> fix: patch mangle for windows

- patches/insider/add-remote-url.patch
This PR adds a command which provides the download url of the reh archive used by the remote extension.
Associated PR: https://github.com/jeanp413/open-remote-ssh/pull/55
> feat: add command to provide reh url

- prepare_vscode.sh
Used on linux to redirect to user to that page.
It doesn't affect macos or windows updates.
> feat: add downloadUrl

- docs/build.md
- icons/build_icons.sh
Fix #1456.
With this fix, i've done other things: 
- Made the logo a little smaller because it felt too big in my opinion. I used `-gravity center` instead of `-geometry +<x>+<y>` option to center it.
- added the dependencies needed for icon generation in the build docs, since there weren't there.
Before :
After :
**Note** : For some reasons the `png2icns` program didn't work on my machine, so i used the generated pngs instead for the comparison. If you can run it, please do it to see if there is no other issues.
> Fix MacOS Icon generation

- .github/workflows/stable-linux.yml
Found that some node packages like `@vscode/ripgrep` had x64 binaries. Traced the issue back to my typo.
> Fix typo in stable-linux

- .github/workflows/insider-linux.yml
- .github/workflows/stable-linux.yml
After the last PR I submitted (#1544), I noticed that the issue with node modules targeting Intel hadn't gone away. After some more careful debugging, I identified the root cause as a difference in the architecture string used to target PowerPC64LE (I was using `ppc64le`, while the expected was `ppc64`).
The line showing the correct string for this is [microsoft/vscode-ripgrep/lib/postinstall.js#L45](https://github.com/microsoft/vscode-ripgrep/blob/643b34e570da705a357ed1edff3f60d3bab4c780/lib/postinstall.js#L45):
```javascript
arch === 'ppc64' ? 'powerpc64le-unknown-linux-gnu' :
```
I've corrected the workflow YAMLs to make use of the proper architecture.
**I must express my sincere apologies for any inconvenience caused due to my previous oversights.**
To make sure that the issue gone, I …
> Fix incorret npm_config_arch for ppc64le

- build/linux/appimage/build.sh
> fix: correctly download pkg2appimage

- prepare_vscode.sh
The PR fixed a bad `product.json` due to a bad path introduced in #1569
> fix: correctly update product.json

- prepare_vscode.sh
Since to rewrite doing in #1569, any failed patching wasn't exiting the build process.
But before the rewrite, the error message wasn't displayed so the if wasn't evaluated since the `git` command was exiting directly.
So this PR is fixing the expected behaviour.
> fix: exit when patching fails

- patches/fix-build-linux.patch
The URL was updated on the vscode repo, but not updated for the patch. Fixing it on this commit.
The code which changed is here: https://github.com/microsoft/vscode/blob/main/build/linux/dependencies-generator.js#L24C1-L25C1
> [vscodium][linux] Fix the patch file for linux builds

- .github/workflows/insider-macos.yml
- .github/workflows/insider-windows.yml
- .github/workflows/stable-macos.yml
- .github/workflows/stable-windows.yml
- prepare_vscode.sh
> fix: use node-v18.17 to generate all artifacts

- .github/workflows/insider-macos.yml
- .github/workflows/insider-spearhead.yml
- .github/workflows/insider-windows.yml
- .github/workflows/stable-macos.yml
- .github/workflows/stable-windows.yml
- insider.json
- patches/brand.patch
- patches/fix-eol-banner.patch
- patches/insider/disable-windows-appx.patch
- product.json
This PR prepares for 1.85.
Windows x86 (32bits) version has been removed.
On Windows, python is fixed to 3.11 due to https://github.com/nodejs/node-gyp/issues/2869
> feat: prepare for 1.85

- patches/update-windows.patch
This PR always send the platform info to the update service do it can find the correct updates.
#1616
> fix: always add platform info for windows

- patches/disable-cloud.patch
Obviously, we don't have access the MS/GitHub cloud. So, let's remove it.
> feat: disable cloud

- patches/update-msi.patch
This PR disables the background install of updates for MSI.
MSI updates can't be done in background since it will asked for the necessary permissions to copy the files in the `Program Files` folder.
#1717
> fix(windows): disable background update for MSI

- src/insider/resources/linux/code.desktop
- src/stable/resources/linux/code.desktop
Upstream [deprecated and removed](https://github.com/microsoft/vscode/commit/0da22a226000adc62cf7b8a83b045668fb8a9296) "unity-launch" flag.
This commit removes this redundant flag from Linux desktop files since it breaks file opening from the outside.
Closes #1865
> Remove deprecated "unity-launch" flag from Linux desktop files

- patches/disable-signature-verification.patch
This PR disables the signature verification due to:
- https://github.com/eclipse/openvsx/pull/928
- https://github.com/eclipse/openvsx/issues/922
> fix: disable signature verification

- check_tags.sh
- release.sh
- stores/snapcraft/check_version.sh
- update_qualityjson.sh
- update_version.sh
Adds support for using this repo in a private Github Enterprise instance.
> Add Github Enterprise support

- package_linux_bin.sh
- Add a check that fails when the riscv electron version doesn't match `.yarnrc`.
- This ensures that we won't produce broken releases when they don't match and signal that the riscv electron version should be bumped.
- Bump riscv electron to v29.4.0.riscv3 for https://github.com/riscv-forks/electron/issues/2
> build(riscv): Check electron version and bump to 29.4.0.riscv3

- stable.json
MS update API doesn't report the correct commit Id so I set it manually.
> feat(1.94.1): manually set correct commit id

- package_linux_reh.sh
> fix(riscv64): bump nodejs to 20.16.0

- .github/workflows/insider-windows.yml
- .github/workflows/stable-windows.yml
- README.md
This PR is adding the signing of the `.exe` and `.msi` installers.
It's provided by [SignPath.io](https://signpath.io) and the certificate is by the [SignPath Foundation](https://signpath.org).
> build(windows): add signing with SignPath

- patches/linux/client/update-xdg-path.patch
This PR is correctly build the `XDG_RUNTIME_DIR` when used inside Flatpak.
> feat(linux): update XDG_RUNTIME_DIR for flatpak

- patches/osx/fix-emulated-urls.patch
> fix(macos): update urls when using emulated app

- .github/workflows/insider-macos.yml
- .github/workflows/stable-macos.yml
This PR upgrades to `macos-13` runner since the `macos-12` has been removed. 
References:
- https://github.com/actions/runner-images/issues/10721
> ci(macos): use available runner

- get_repo.sh
- patches/insider/add-remote-url.patch
- patches/version-0-release.patch
- patches/version-1-update.patch
- prepare_vscode.sh
The new version number use the standard `MAJOR.MINOR.PATCH`.
But our patch number will be constructed as: `<VSCode's patch number><time based between 0 and 9999>`
VSCode has never released more than 5 patches so the max patch number is 5 so we can keep our patch number under 65,535.
It will solve:
- `.msi` only supports the first 3 numbers when updating. 
- allow us to have several releases on the same day. Don't have to wait for the next day for deploying a hotfix...
> feat: new version number

- patches/version-0-release.patch
This PR removes the leading zeros in the patch number of the version number.
Reference:
- #2301
> fix: remove leading zeros before passing version to extension

- patches/add-remote-url.patch
- patches/insider/add-remote-url.patch
- utils.sh
Now, the extension has the version without the leading zero so the generated url isn't correct.
And `}` was missing.
Hard coding the version fix the issue.
References:
- #2303
> fix: hard code version in server template

- build/linux/package_reh.sh
This PR fixes the incorrect `ripgrep.sh` path specified in `package_reh.sh`, causing `rg` binary of REH server not being replaced with native ones.
> fix(reh): use correct ripgrep.sh path

- README.md
I thought it would be nicer to jump into the note instead of scrolling through the index :slightly_smiling_face:
> Update "proprietary debugger extensions" note link in README.md
